# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - global-gutstavo-lucas

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_c307b705c3f3444da6fe0f1b288fc0d1 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_cc5040e58f23433fbf27c0f09739bcad }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_c307b705c3f3444da6fe0f1b288fc0d1 }}/global:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'global-gutstavo-lucas'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b5e64138eab6405b95031d1b0b509e05 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_c307b705c3f3444da6fe0f1b288fc0d1 }}/global:${{ github.sha }}'